-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
ROUND(AVG(R.REVIEW_SCORE),2)  SCORE
FROM REST_REVIEW AS R 
JOIN REST_INFO AS I ON I.REST_ID = R.REST_ID
GROUP BY REST_ID
HAVING I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, I.FAVORITES DESC;

# SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
# ROUND(AVG(R.REVIEW_SCORE),2) SCORE
# FROM REST_REVIEW R , REST_INFO I
# WHERE R.REST_ID = I.REST_ID
# AND I.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, I.FAVORITES DESC;